[[edge_functions]]
function = "entry"
path = "/*"
import_map = "./src/import_map.json"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  # Sanity Environment Variables
  PUBLIC_SANITY_PROJECT_ID = "qpes3s7p"
  PUBLIC_SANITY_DATASET = "production"
  PUBLIC_SANITY_API_VERSION = "2024-03-01"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]
  external_node_modules = ["sharp"]

[dev]
  command = "npm run dev"
  targetPort = 4321

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; connect-src 'self' https: wss:; frame-ancestors 'none';"