[[edge_functions]]
function = "entry"
path = "/*"
import_map = "./src/import_map.json"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry-server"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
NODE_VERSION = "20.11.0"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["dist/**/*"]

[dev]
  command = "npm run dev"
  targetPort = 4321

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"