[[edge_functions]]
function = "entry"
path = "/*"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.11.0"
  PUBLIC_SANITY_PROJECT_ID = "qpes3s7p"
  PUBLIC_SANITY_DATASET = "production"
  PUBLIC_SANITY_API_VERSION = "2024-03-01"
  ESBUILD_VERSION = "0.24.2"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["sharp"]
  included_files = ["dist/**/*"]

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"